//post insights
export const POST_INSIGHTS = "POST INSIGHTS";
export const POST_INSIGHT_ERROR = "POST INSIGHT ERROR";
export const POST_INSIGHT_LOADING = "POST INSIGHT LOADING";

//get insights

export const GET_INSIGHTS = "GET INSIGHTS";
export const GET_INSIGHT_ERROR = "GET INSIGHT ERROR";
export const GET_INSIGHT_LOADING = "GET INSIGHT LOADING";

export const GET_SINGLE_INSIGHT = "GET SINGLE INSIGHT";
export const GET_SINGLE_INSIGHT_ERROR = "GET SINGLE INSIGHT ERROR";
export const GET_SINGLE_INSIGHT_LOADING = "GET SINGLE INSIGHT LOADING";
